import { FaReact, FaNodeJs, FaGitAlt } from "react-icons/fa";

import {
  SiJavascript,
  SiMongodb,
  SiExpress,
  SiTailwindcss,
  SiRedux,
  SiPostman,
  SiFirebase,
  SiVite,
} from "react-icons/si";

export const skills = [
  {
    name: "React.js",
    icon: FaReact,
    percentage: 95,
    level: "Expert",
    category: "Frontend",
    color: "#61DAFB",
  },
  {
    name: "JavaScript",
    icon: SiJavascript,
    percentage: 92,
    level: "Expert",
    category: "Language",
    color: "#F7DF1E",
  },
  {
    name: "Node.js",
    icon: FaNodeJs,
    percentage: 90,
    level: "Advanced",
    category: "Backend",
    color: "#68A063",
  },
  {
    name: "Express.js",
    icon: SiExpress,
    percentage: 88,
    level: "Advanced",
    category: "Backend",
    color: "#ffffff",
  },
  {
    name: "MongoDB",
    icon: SiMongodb,
    percentage: 90,
    level: "Advanced",
    category: "Database",
    color: "#13AA52",
  },
  {
    name: "Tailwind CSS",
    icon: SiTailwindcss,
    percentage: 94,
    level: "Expert",
    category: "CSS Framework",
    color: "#38BDF8",
  },
  {
    name: "Redux Toolkit",
    icon: SiRedux,
    percentage: 86,
    level: "Advanced",
    category: "State Management",
    color: "#764ABC",
  },
  {
    name: "Git & GitHub",
    icon: FaGitAlt,
    percentage: 90,
    level: "Advanced",
    category: "Version Control",
    color: "#F1502F",
  },
  {
    name: "Postman",
    icon: SiPostman,
    percentage: 88,
    level: "Advanced",
    category: "API Testing",
    color: "#FF6C37",
  },
  {
    name: "Firebase",
    icon: SiFirebase,
    percentage: 80,
    level: "Intermediate",
    category: "Backend Service",
    color: "#FFCA28",
  },
  {
    name: "Vite",
    icon: SiVite,
    percentage: 92,
    level: "Expert",
    category: "Build Tool",
    color: "#8B5CF6",
  },
];
